---
- name: Configuration templating using include statement
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Generate config files
    template: src=ninjatempl1.j2 dest=configs/{{ item.hostname }}.txt
    with_items:
      - {hostname: router1, default_gateway: 1.1.1.1}
      - {hostname: router2, default_gateway: 1.1.2.1}
      - {hostname: router3, default_gateway: 1.1.3.1}
      - {hostname: router4, default_gateway: 1.1.4.1}
