---
- name: Configuration templating using include statement
  hosts: localhost
  gather_facts: false
  tasks:

  - name: Generate config files
    template: src=ninjatempl4.j2 dest=configs/{{ item.hostname }}.txt
    with_items:
      - {hostname: switch1, default_gateway: 1.1.1.1, model_interfaces: 2601.j2, ip_addr: 1.1.1.5, netmask: 255.255.255.0,
	interfaces: [
	    {name: FastEthernet0, switchport_mode: access},
            {name: FastEthernet1, switchport_mode: access},
            {name: FastEthernet2, switchport_mode: access},
            {name: FastEthernet3, switchport_mode: trunk},
            {name: FastEthernet4, switchport_mode: trunk}
		    ]}
      - {hostname: switch2, default_gateway: 1.1.2.1, model_interfaces: 2602.j2, ip_addr: 1.1.2.5, netmask: 255.255.255.0,
	interfaces: [
            {name: FastEthernet0, switchport_mode: access},
            {name: FastEthernet1, switchport_mode: access},
            {name: FastEthernet2, switchport_mode: access},
            {name: FastEthernet3, switchport_mode: trunk},
            {name: FastEthernet4, switchport_mode: trunk}
                    ]}
      - {hostname: switch3, default_gateway: 1.1.3.1, model_interfaces: 2603.j2, ip_addr: 1.1.3.5, netmask: 255.255.255.0,
	interfaces: [
            {name: FastEthernet0, switchport_mode: access},
            {name: FastEthernet1, switchport_mode: access},
            {name: FastEthernet2, switchport_mode: access},
            {name: FastEthernet3, switchport_mode: trunk},
            {name: FastEthernet4, switchport_mode: trunk}
                    ]}
      - {hostname: switch4, default_gateway: 1.1.4.1, model_interfaces: 2604.j2, ip_addr: 1.1.4.5, netmask: 255.255.255.0,
	interfaces: [
            {name: FastEthernet0, switchport_mode: access},
            {name: FastEthernet1, switchport_mode: access},
            {name: FastEthernet2, switchport_mode: access},
            {name: FastEthernet3, switchport_mode: trunk},
            {name: FastEthernet4, switchport_mode: trunk}
                    ]}
